# Generated by Django 5.0 on 2024-11-20 17:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirstSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(db_index=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])])),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='is_active', verbose_name='is_active')),
                ('title', models.CharField(db_index=True, help_text='title', max_length=100, verbose_name='title')),
                ('description', models.TextField(db_index=True, help_text='description', verbose_name='description')),
                ('link', models.URLField(blank=True, db_index=True, help_text='link to forward', null=True, verbose_name='link to forward')),
            ],
            options={
                'verbose_name': 'slider',
                'verbose_name_plural': 'slider',
            },
        ),
    ]
