# Generated by Django 5.0 on 2024-11-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstslider',
            name='test',
            field=models.TextField(blank=True, null=True),
        ),
    ]
