# Generated by Django 5.0 on 2024-11-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_firstslider_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firstslider',
            name='test',
        ),
        migrations.AddField(
            model_name='firstslider',
            name='link_to_go',
            field=models.URLField(blank=True, db_index=True, help_text='link', null=True, verbose_name='link'),
        ),
    ]
