# Generated by Django 5.0 on 2024-11-20 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_firstslider_test_firstslider_link_to_go'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firstslider',
            name='link',
        ),
    ]
