# Generated by Django 5.0 on 2024-11-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(db_index=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=100)),
                ('city', models.CharField(db_index=True, max_length=150)),
                ('is_active', models.BooleanField(blank=True, db_index=True, default=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='created time', verbose_name='created time')),
                ('updated', models.DateTimeField(auto_now=True, db_column='updated', db_index=True, help_text='updated time', verbose_name='updated time')),
            ],
        ),
    ]
