# Generated by Django 5.0 on 2024-12-08 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, help_text='name', max_length=150, null=True, verbose_name='name')),
                ('phone', models.CharField(blank=True, db_index=True, help_text='phone', max_length=150, null=True, verbose_name='phone')),
                ('text', models.TextField(blank=True, db_index=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='created time', verbose_name='created time')),
                ('updated', models.DateTimeField(auto_now=True, db_column='updated', db_index=True, help_text='updated time', verbose_name='updated time')),
            ],
        ),
    ]
