# Generated by Django 5.0 on 2024-12-02 14:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('card', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Copon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expire', models.DateTimeField(blank=True, db_index=True, help_text='expire time', null=True, verbose_name='expire time')),
                ('copon_code', models.CharField(db_column='copon_code', db_index=True, help_text='cpon code', max_length=15, verbose_name='copon code')),
                ('is_active', models.BooleanField(blank=True, db_index=True, help_text='is active', null=True, verbose_name='is active')),
                ('percent', models.PositiveIntegerField(blank=True, db_index=True, help_text='percent', null=True, verbose_name='percent')),
                ('number_code', models.PositiveIntegerField(db_column='number_code', db_index=True, default=10, help_text='number code', verbose_name='number code')),
            ],
            options={
                'verbose_name': 'copon',
                'verbose_name_plural': 'copon',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_hash', models.CharField(blank=True, db_column='card_hash', db_index=True, help_text='card hash', max_length=250, null=True, verbose_name='card hash')),
                ('card_pan', models.CharField(blank=True, db_column='card_pan', db_index=True, help_text='card_pan', max_length=250, null=True, verbose_name='card_pan')),
                ('ref_id', models.CharField(blank=True, db_column='ref_id', db_index=True, help_text='ref_id', max_length=250, null=True, verbose_name='ref_id')),
                ('bank_name', models.CharField(blank=True, db_column='bank_name', db_comment='bank name', db_index=True, help_text='اسم بانک', max_length=150, null=True, verbose_name='اسم بانک')),
                ('bank_status', models.CharField(blank=True, db_column='bank_status', db_comment='bank_status', db_index=True, help_text='وضعیت بانک', max_length=150, null=True, verbose_name='وضعیت بانک')),
                ('tracking_code', models.CharField(blank=True, db_column='tracking_code', db_comment='tracking_code', db_index=True, help_text='tracking_code', max_length=150, null=True, verbose_name='tracking_code')),
                ('amount', models.FloatField(blank=True, db_index=True, help_text='مقدار', null=True, verbose_name='مقدار')),
                ('created', models.DateTimeField(auto_now_add=True, db_column='created', db_comment='created time', db_index=True, help_text='زمان ساخت', null=True, verbose_name='زمان ساخت')),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, help_text='زمان اخرین تغییر ', null=True, verbose_name='زمان اخرین تغییر')),
                ('user', models.ForeignKey(blank=True, db_column='user', help_text='کاربر', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پرداخت ها',
                'verbose_name_plural': 'پرداخت ها',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(db_column='id', db_comment='id', db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('send_status', models.CharField(blank=True, choices=[('درانتظار یافتن اولین پیک', 'درانتظار یافتن اولین پیک'), ('پیک بسته را تحویل گرفت', 'پیک بسته را تحویل گرفت'), ('بسته تحویل داده شد', 'بسته تحویل داده شد')], db_index=True, default='درانتظار یافتن اولین پیک', help_text='وضیعت تحویل', max_length=40, null=True, verbose_name='وضیعت تحویل')),
                ('authority', models.CharField(blank=True, db_column='authority', db_comment='Authority', db_index=True, help_text='Authority', max_length=200, null=True, verbose_name='Authority')),
                ('name', models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='name')),
                ('last_name', models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='last_name')),
                ('order_status', models.CharField(choices=[('PAID', 'paid'), ('NOTPAID', 'notpaid')], db_column='order_status', db_index=True, default='NOTPAID', help_text='order status', max_length=110, verbose_name='order status')),
                ('custom_order_id', models.CharField(blank=True, db_column='custom_order_id', db_index=True, max_length=40, null=True)),
                ('amount', models.FloatField(blank=True, db_index=True, null=True)),
                ('final_amount', models.FloatField(blank=True, db_index=True, null=True)),
                ('used_copon', models.BooleanField(db_index=True, default=False, help_text='used copon', verbose_name='used copon')),
                ('city', models.CharField(blank=True, db_index=True, help_text='city', max_length=120, null=True, verbose_name='city')),
                ('address', models.TextField(blank=True, db_index=True, help_text='address', max_length=450, null=True, verbose_name='address')),
                ('zipcode', models.CharField(blank=True, db_index=True, help_text='zipcode', max_length=40, null=True, verbose_name='zipcode')),
                ('phone', models.CharField(blank=True, db_index=True, help_text='phone', max_length=40, null=True, verbose_name='phone')),
                ('email', models.EmailField(blank=True, db_index=True, help_text='email', max_length=140, null=True, verbose_name='email')),
                ('is_paid', models.BooleanField(db_index=True, default=False, help_text='is paid', verbose_name='is paid')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='created', null=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, help_text='updated', null=True, verbose_name='updated')),
                ('items', models.ManyToManyField(db_index=True, help_text='cart item', to='card.cartitem', verbose_name='cart item')),
                ('user', models.ForeignKey(blank=True, help_text='user', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('payment', models.ForeignKey(blank=True, help_text='payment', null=True, on_delete=django.db.models.deletion.CASCADE, to='order.payment', verbose_name='payment')),
            ],
        ),
    ]
